import type { Question } from "$lib/types";

export { questions };
const questions: Question[] = [
    { question: "Death is no doubt a grim experience.", category: "Fear of Death" },
    { question: "The prospects of my own death arouses anxiety in me.", category: "Fear of Death" },
    { question: "I avoid death thoughts at all costs.", category: "Fear of Death" },
    { question: "I believe that I will be in heaven after I die.", category: "Fear of Death" },
    { question: "Death will bring an end to all my troubles.", category: "Fear of Death" },
    { question: "Death should be viewed as a natural, undeniable, and unavoidable event.", category: "Neutral Acceptance" },
    { question: "I am disturbed by the finality of death.", category: "Fear of Death" },
    { question: "Death is an entrance to a place of ultimate satisfaction.", category: "Approach Acceptance" },
    { question: "Death provides an escape from this terrible world.", category: "Escape Acceptance" },
    { question: "Whenever the thought of death enters my mind, I try to push it away.", category: "Fear of Death" },
    { question: "Death is deliverance from pain and suffering.", category: "Fear of Death" },
    { question: "I always try not to think about death.", category: "Death Avoidance" },
    { question: "I believe that heaven will be a much better place than this world.", category: "Fear of Death" },
    { question: "Death is a natural aspect of life.", category: "Neutral Acceptance" },
    { question: "Death is a union with God and eternal bliss.", category: "Approach Acceptance" },
    { question: "Death brings a promise of a new and glorious life.", category: "Approach Acceptance" },
    { question: "I would neither fear death nor welcome it.", category: "Neutral Acceptance" },
    { question: "I have an intense fear of death.", category: "Fear of Death" },
    { question: "I avoid thinking about death altogether.", category: "Death Avoidance" },
    { question: "The subject of life after death troubles me greatly.", category: "Fear of Death" },
    { question: "The fact that death will mean the end of everything as I know it frightens me.", category: "Fear of Death" },
    { question: "I look forward to a reunion with my loved ones after I die.", category: "Approach Acceptance" },
    { question: "I view death as a relief from earthly suffering.", category: "Approach Acceptance" },
    { question: "Death is simply a part of the process of life.", category: "Neutral Acceptance" },
    { question: "I see death as a passage to an eternal and blessed place.", category: "Approach Acceptance" },
    { question: "I try to have nothing to do with the subject of death.", category: "Death Avoidance" },
    { question: "Death offers a wonderful release of the soul.", category: "Approach Acceptance" },
    { question: "One thing that gives me comfort in facing death is my belief in the afterlife.", category: "Approach Acceptance" },
    { question: "I see death as a relief from the burden of this life.", category: "Escape Acceptance" },
    { question: "Death is neither good nor bad.", category: "Neutral Acceptance" },
    { question: "I look forward to life after death.", category: "Approach Acceptance" },
    { question: "The uncertainty of not knowing what happens after death worries me.", category: "Fear of Death" },
  ];
